bookstore-mvc/Controllers/AuthorsController.cs
using bookstore_mvc.Data.Services;
using bookstore_mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace bookstore_mvc.Controllers
{
  [Route("[controller]")]
  public class AuthorsController : Controller
  {
    private readonly IAuthorsService _service;

    public AuthorsController(IAuthorsService service)
    {
      _service = service;
    }

    public async Task<IActionResult> Index()
    {
      var allAuthors = await _service.GetAllAsync();
      return View(allAuthors);
    }

    [HttpGet("Info/{id}")]
    public async Task<IActionResult> Info(int id)
    {
      var authorInfo = await _service.GetAuthorByIdAsync(id);

      if (authorInfo == null)
      {
        return View("NotFound");
      }

      return View(authorInfo);
    }

    [HttpGet("Create")]
    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    [Route("Create")]
    public async Task<IActionResult> Create([Bind("ImageURL,Name,Biography")] Author author)
    {
      if (!ModelState.IsValid)
      {
        return View(author);
      }
      await _service.AddAsync(author);
      
      return RedirectToAction(nameof(Index));
    }

    [HttpGet("Edit/{id}")]
    public async Task<IActionResult> Edit(int id)
    {
      var authorInfo = await _service.GetByIdAsync(id);
      if (authorInfo == null) return View("NotFound");
      return View(authorInfo);
    }

    [HttpPost]
    [Route("Edit/{id}")]
    public async Task<IActionResult> Edit(int id, [Bind("Id,ImageURL,Name,Biography")] Author author)
    {
      if (!ModelState.IsValid) return View(author);

      if (id == author.Id)
      {
        await _service.UpdateAsync(id, author);
        return RedirectToAction(nameof(Index));
      }
      return View(author);
    }

    [HttpGet("Delete/{id}")]
    public async Task<IActionResult> Delete(int id)
    {
      var authorInfo = await _service.GetAuthorByIdAsync(id);
      if (authorInfo == null) return View("NotFound");
      return View(authorInfo);
    }

    [HttpPost, ActionName("Delete")]
    [Route("Delete/{id}")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var authorInfo = await _service.GetAuthorByIdAsync(id);
      if (authorInfo == null) return View("NotFound");

      await _service.DeleteAsync(id);
      return RedirectToAction(nameof(Index));
    }

    // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    // public IActionResult Error()
    // {
    //   return View("Error!");
    // }
  }
}

bookstore-mvc/Controllers/BooksController.cs
using bookstore_mvc.Data.Services;
using bookstore_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace bookstore_mvc.Controllers
{
  [Route("[controller]")]
  public class BooksController : Controller
  {
    private readonly IBooksService _service;

    public BooksController(IBooksService service)
    {
      _service = service;
    }

    // [HttpGet("all")]
    // public async Task<ActionResult<List<Book>>> GetBooks()
    // {
    //     return await _context.Books.ToListAsync();
    // }

    // [HttpGet("{Id}")]
    // public async Task<ActionResult<Book>> GetBook(int Id)
    // {
    //     return await _context.Books.FindAsync(Id);
    // }

    // public async Task<IActionResult> Index()
    // {
    //   var allBooks = await _service.GetAllAsync(n => n.Author);
    //   return View(allBooks);
    // }

    // [HttpPost]
    public async Task<IActionResult> Search(string searchString, int selectedAuthor, int selectedPublisher, int selectedGenre)
    {
      var allBooks = await _service.GetAllAsync(n => n.Author);

      var dropdownsData = await _service.GetBookDroupownMenuValues();
      ViewBag.Authors = new SelectList(dropdownsData.Authors, "Id", "Name");
      ViewBag.Publishers = new SelectList(dropdownsData.Publishers, "Id", "Name");

      if (!string.IsNullOrEmpty(searchString))
      {
        var searchBooks = allBooks.Where(n => n.Title.ToLower().Contains(searchString.ToLower())).ToList();
        if (searchBooks.Any())
        {
          return View("Index", searchBooks);
        }
        else
        {
          return View("NotFound");
        }
      }

      if (selectedAuthor != 0)
      {
        var filteredBooks = allBooks.Where(n => n.AuthorId == selectedAuthor).ToList();
        return View("Index", filteredBooks);
      }

      if (selectedPublisher != 0)
      {
        var filteredBooks = allBooks.Where(n => n.PublisherId == selectedPublisher).ToList();
        return View("Index", filteredBooks);
      }

      if (selectedGenre != 0)
      {
        var filteredBooks = allBooks.Where(n => (int)n.Genre == selectedGenre).ToList();
        return View("Index", filteredBooks);
      }

      // if (selectedAuthor != 0 && selectedPublisher != 0)
      // {
      //   var filteredBooks = allBooks.Where(n => n.AuthorId == selectedAuthor && n.PublisherId == selectedPublisher).ToList();
      //   return View("Index", filteredBooks);
      // }

      return View("Index", allBooks);
    }

    // [HttpPost]
    // public async Task<IActionResult> Search(int selectedItem)
    // {
    //   var allBooks = await _service.GetAllAsync(n => n.Author);

    //   var dropdownsData = await _service.GetBookDroupownMenuValues();
    //   ViewBag.Authors = new SelectList(dropdownsData.Authors, "Id", "Name");
    //   ViewBag.Publishers = new SelectList(dropdownsData.Publishers, "Id", "Name");

    //   if (selectedItem != -1)
    //   {
    //     var searchBooks = allBooks.Where(n => n.AuthorId == selectedItem).ToList();

    //     return View("Index", searchBooks);
    //   }

    //   return View("Index", allBooks);
    // }

    //Get: Books/Create
    [HttpGet("Create")]
    public async Task<IActionResult> Create()
    {
      var dropdownsData = await _service.GetBookDroupownMenuValues();

      ViewBag.Authors = new SelectList(dropdownsData.Authors, "Id", "Name");
      ViewBag.Publishers = new SelectList(dropdownsData.Publishers, "Id", "Name");

      return View();
    }

    [HttpPost]
    [Route("Create")]
    public async Task<IActionResult> Create(NewBookVM book)
    {
      if (!ModelState.IsValid)
      {
        var dropdownsData = await _service.GetBookDroupownMenuValues();

        ViewBag.Authors = new SelectList(dropdownsData.Authors, "Id", "Name");
        ViewBag.Publishers = new SelectList(dropdownsData.Publishers, "Id", "Name");

        return View(book);
      }

      await _service.AddNewBookAsync(book);
      return RedirectToAction(nameof(Index));
    }

    // [HttpPost]
    // [Route("Create")]
    // public async Task<IActionResult> Create([Bind("ImageURL,Title,Pages,Price,Quantity,Genre,Author")] Book book)
    // {
    //   if (!ModelState.IsValid)
    //   {
    //     return View(book);
    //   }
    //   await _service.AddAsync(book);
    //   return RedirectToAction(nameof(Index));
    // }

    [HttpGet("Info/{id}")]
    public async Task<IActionResult> Info(int id)
    {
      var bookInfo = await _service.GetBookByIdAsync(id);

      if (bookInfo == null)
      {
        return View("NotFound");
      }

      return View(bookInfo);
    }

    //Get: Books/Edit/id
    [HttpGet("Edit/{id}")]
    public async Task<IActionResult> Edit(int id)
    {
      var bookInfo = await _service.GetBookByIdAsync(id);

      if (bookInfo == null)
      {
        return View("NotFound");
      }

      var response = new NewBookVM()
      {
        Id = bookInfo.Id,
        ImageURL = bookInfo.ImageURL,
        Title = bookInfo.Title,
        Pages = bookInfo.Pages,
        Price = bookInfo.Price,
        Quantity = bookInfo.Quantity,
        Genre = bookInfo.Genre,
        AuthorId = bookInfo.AuthorId,
        PublisherId = bookInfo.PublisherId
      };

      var dropdownsData = await _service.GetBookDroupownMenuValues();

      ViewBag.Authors = new SelectList(dropdownsData.Authors, "Id", "Name");
      ViewBag.Publishers = new SelectList(dropdownsData.Publishers, "Id", "Name");

      return View(response);
    }

    [HttpPost]
    [Route("Edit/{id}")]
    public async Task<IActionResult> Edit(int id, NewBookVM book)
    {
      if (id != book.Id)
      {
        return View("NotFound");
      }

      if (!ModelState.IsValid)
      {
        var dropdownsData = await _service.GetBookDroupownMenuValues();

        ViewBag.Authors = new SelectList(dropdownsData.Authors, "Id", "Name");
        ViewBag.Publishers = new SelectList(dropdownsData.Publishers, "Id", "Name");

        return View(book);
      }

      await _service.UpdateBookAsync(book);
      return RedirectToAction(nameof(Index));
    }

    // [HttpPost]
    // [Route("Edit/{id}")]
    // public async Task<IActionResult> Edit(int id, [Bind("Id,ImageURL,Title,Pages,Price,Quantity,Genre,Author")] Book book)
    // {
    //   if (!ModelState.IsValid)
    //   {
    //     return View(book);
    //   }
    //   await _service.UpdateAsync(id, book);
    //   return RedirectToAction(nameof(Index));
    // }


    //Get: Books/Delete/1
    [HttpGet("Delete/{id}")]
    public async Task<IActionResult> Delete(int id)
    {
      var bookInfo = await _service.GetBookByIdAsync(id);

      if (bookInfo == null)
      {
        return View("NotFound");
      }

      return View(bookInfo);
    }

    [HttpPost, ActionName("Delete")]
    [Route("Delete/{id}")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var bookInfo = await _service.GetBookByIdAsync(id);

      if (bookInfo == null)
      {
        return View("NotFound");
      }

      await _service.DeleteAsync(id);
      return RedirectToAction(nameof(Index));
    }



    // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    // public IActionResult Error()
    // {
    //   return View("Error!");
    // }
  }
}

bookstore-mvc/Controllers/OrdersController.cs
using System.Security.Claims;
using bookstore_mvc.Data.Cart;
using bookstore_mvc.Data.Services;
using bookstore_mvc.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace bookstore_mvc.Controllers
{
  [Route("[controller]")]
  public class OrdersController : Controller
  {
    private readonly IBooksService _booksService;
    private readonly ShoppingCart _shoppingCart;
    private readonly IOrdersService _ordersService;

    public OrdersController(IBooksService booksService, ShoppingCart shoppingCart, IOrdersService ordersService)
    {
      _booksService = booksService;
      _shoppingCart = shoppingCart;
      _ordersService = ordersService;
    }

    [HttpGet("Index")]
    public async Task<IActionResult> Index()
    {
      string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      string userRole = User.FindFirstValue(ClaimTypes.Role);

      var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
      return View(orders);
    }

    [HttpGet("ShoppingCart")]
    public IActionResult ShoppingCart()
    {
      var items = _shoppingCart.GetShoppingCartItems();
      _shoppingCart.ShoppingCartItems = items;

      var response = new ShoppingCartVM()
      {
        ShoppingCart = _shoppingCart,
        ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
      };

      return View(response);
    }

    [HttpGet("AddItemToShoppingCart")]
    public async Task<IActionResult> AddItemToShoppingCart(int id)
    {
      var book = await _booksService.GetBookByIdAsync(id);

      if (book != null)
      {
        _shoppingCart.AddItemToCart(book);
      }
      return base.RedirectToAction(nameof(Data.Cart.ShoppingCart));
    }

    public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
    {
      var book = await _booksService.GetBookByIdAsync(id);

      if (book != null)
      {
        _shoppingCart.RemoveItemFromCart(book);
      }
      return RedirectToAction(nameof(ShoppingCart));
    }

    [HttpGet("CompleteOrder")]
    public async Task<IActionResult> CompleteOrder()
    {
      var items = _shoppingCart.GetShoppingCartItems();
      string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

      await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
      await _shoppingCart.ClearShoppingCartAsync();

      return View("OrderSuccess");
    }

    // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    // public IActionResult Error()
    // {
    //   return View("Error!");
    // }
  }
}

bookstore-mvc/Controllers/PublishersController.cs
using bookstore_mvc.Data.Services;
using bookstore_mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace bookstore_mvc.Controllers
{
  [Route("[controller]")]
  public class PublishersController : Controller
  {
    private readonly IPublishersService _service;

    public PublishersController(IPublishersService service)
    {
      _service = service;
    }

    public async Task<IActionResult> Index()
    {
      var allPublishers = await _service.GetAllAsync();
      return View(allPublishers);
    }

    [HttpGet("Info/{id}")]
    public async Task<IActionResult> Info(int id)
    {
      var publisherInfo = await _service.GetPublisherByIdAsync(id);

      if (publisherInfo == null)
      {
        return View("NotFound");
      }

      return View(publisherInfo);
    }

    [HttpGet("Create")]
    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    [Route("Create")]
    public async Task<IActionResult> Create([Bind("ImageURL,Name,About")] Publisher publisher)
    {
      if (!ModelState.IsValid)
      {
        return View(publisher);
      }
      await _service.AddAsync(publisher);

      return RedirectToAction(nameof(Index));
    }

    [HttpGet("Edit/{id}")]
    public async Task<IActionResult> Edit(int id)
    {
      var publisherInfo = await _service.GetByIdAsync(id);
      if (publisherInfo == null) return View("NotFound");
      return View(publisherInfo);
    }

    [HttpPost]
    [Route("Edit/{id}")]
    public async Task<IActionResult> Edit(int id, [Bind("Id,ImageURL,Name,About")] Publisher publisher)
    {
      if (!ModelState.IsValid) return View(publisher);

      if (id == publisher.Id)
      {
        await _service.UpdateAsync(id, publisher);
        return RedirectToAction(nameof(Index));
      }
      return View(publisher);
    }

    [HttpGet("Delete/{id}")]
    public async Task<IActionResult> Delete(int id)
    {
      var publisherInfo = await _service.GetPublisherByIdAsync(id);
      if (publisherInfo == null) return View("NotFound");
      return View(publisherInfo);
    }

    [HttpPost, ActionName("Delete")]
    [Route("Delete/{id}")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var publisherInfo = await _service.GetPublisherByIdAsync(id);
      if (publisherInfo == null) return View("NotFound");

      await _service.DeleteAsync(id);
      return RedirectToAction(nameof(Index));
    }

  }
}

bookstore-mvc/Views/Shared/NotFound.cshtml
<div class="section center-caption">
  <h3 class="title">You are searching for a nonexistent item :(</h3>
  <img class="img" src="/img/UnknownBook.png" alt="Unknown Book">
  <a class="btn reversed" asp-controller="Books" asp-action="Index">
			<i class="fa-solid fa-left-long"></i>
			<span class="btn__text">Go Back to Home Page</span>
		</a>
</div>

bookstore-mvc/Views/Shared/_AddNewItem.cshtml
@model string;

@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
  <a class="fixed-btn" asp-controller="@Model" asp-action="Create">
    <span class="btn__text">Add New</span>
    <i class="fa-solid fa-plus"></i>
  </a>
}

bookstore-mvc/Views/Shared/_AuthLayout.cshtml
@{
  Layout = "/Views/Shared/_Layout.cshtml";
}

<section class="auth">
  <div class="auth__right">
    <ul class="auth__list auth-list">
      <li class="auth-list__item">
        <a class="auth-list__link" asp-controller="Account" asp-action="Login">Sign In</a>
      </li>
      <li class="auth-list__item">
        <a class="auth-list__link" asp-controller="Account" asp-action="Register">Sign Up</a>
      </li>
    </ul>

    <div class="auth__content">
      @RenderBody()
    </div>
  </div>

  <div class="auth__left"></div>
</section>

@section Scripts{
  @RenderSection("Scripts", required: false)

  <script>
    const authListLinks = document.querySelectorAll(".auth-list__link");
    const current = location.pathname;

    console.log(authListLinks);
    console.log(current);

    authListLinks.forEach((link) => {
      if(current.indexOf(link.getAttribute("href")) !== -1) {
        link.parentNode.classList.toggle("auth-list__item--active");
      }
    })
  </script>
}

bookstore-mvc/Views/Shared/_AuthNavigation.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
  <li class="header__item">
    <a class="header__link" data-bs-toggle="collapse" href="#collapse-user" role="button" aria-expanded="false" aria-controls="collapse-user">
      <i class="text-light fa-solid fa-user"></i>
    </a>
  </li> 
  <ul class="header__list--account collapse" id="collapse-user">
    <li class="header__item">
      <a class="header__link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
    </li>
  </ul>
}
else 
{
  <li class="header__item">
    <a class="text-light" data-bs-toggle="collapse" href="#collapse-user" role="button" aria-expanded="false" aria-controls="collapse-user">
      <i class="text-light fa-solid fa-user"></i>
    </a>
  </li> 
  <ul class="header__list--account collapse" id="collapse-user">
    <li class="header__item">
      <a class="header__link username" asp-area="" asp-controller="Account" asp-action="Index">@UserManager.GetUserName(User)</a>
    </li>
    <li class="header__item">
      <a class="header__link" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
    </li>
    <li class="header__item">
      <form class="text-light" asp-controller="Account" asp-action="Logout">
        <button class="btn">Logout</button>
      </form>
    </li>
  </ul>
}

bookstore-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A better way to buy books online. Here you can buy interesting books for children and adults">
    <title>@ViewData["Title"] - bookstore_mvc</title>
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/img/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/icons/favicon-16x16.png">
    <link rel="manifest" href="~/img/icons/site.webmanifest">
    <link rel="mask-icon" href="~/img/icons/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="~/img/icons/favicon.ico">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="msapplication-config" content="~/img/icons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/bookstore_mvc.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-toggleable-md navbar-light">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="header">
                    <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="logo__img" src="/img/icons/logo.svg" alt="Logo">
                    </a>
            		<form class="header__form" asp-controller="Books" asp-action="Search">
                        <input name="searchString" type="text" placeholder="Search for a book...">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </form>
            		<ul class="header__links navbar-collapse collapse">
                        @await Html.PartialAsync("_AuthNavigation")
            			@await Component.InvokeAsync("DisplayCartQuantity")
            		</ul>
            		<ul class="header__list navbar-collapse collapse">
            			<li class="header__item">
                            <a class="header__link" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
            			</li>
            			<li class="header__item">
                            <a class="header__link" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
            			</li>
            			<li class="header__item">
                            <a class="header__link" asp-area="" asp-controller="Publishers" asp-action="Index">Publishers</a>
            			</li>
            		</ul>
                    <ul class="header__links navbar-collapse collapse">
                        <li class="header__item">
            		        <a class="header__link" asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                        </li>
                    </ul>
                </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted dark bg-black">
        <div class="container text-light text-center">
            &copy; 2022 Vira Vakhovska. All rights reserved.</a>
        </div>
    </footer>
    <script src="https://kit.fontawesome.com/b983d82776.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>